--DELETE FROM ORDER_MASTER;

DROP TABLE IF EXISTS ORDER_MASTER;
  
CREATE TABLE ORDER_MASTER (
  ORDER_ID 				INT 			AUTO_INCREMENT  PRIMARY KEY,
  USER_ID 				INT 			NOT NULL,
  SERVICE_PROVIDER_ID 	INT 			NOT NULL,
  SERVICE_ID			INT			 	NOT NULL,
  JOB_REMARKS 			VARCHAR(250) 	NOT NULL,
  AMOUNT 				VARCHAR(250) 	NOT NULL,
  STATUS 				VARCHAR(250) 	NOT NULL,
  SERVICE_DATE 			DATE			NOT NULL
);